<?php

/**
 * @file
 * Contains wishlist_template.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wishlist_template_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wishlist_template module.
    case 'help.page.wishlist_template':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Description') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function wishlist_template_theme() {
  $theme = [];
  $theme['wishlist_template'] = array(
    'render element' => 'elements',
    'file' => 'wishlist_template.page.inc',
    'template' => 'wishlist_template',
  );
  $theme['wishlist_template_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'wishlist_template.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function wishlist_template_theme_suggestions_wishlist_template(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#wishlist_template'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'wishlist_template__' . $sanitized_view_mode;
  $suggestions[] = 'wishlist_template__' . $entity->bundle();
  $suggestions[] = 'wishlist_template__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'wishlist_template__' . $entity->id();
  $suggestions[] = 'wishlist_template__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Callback function that returns a list of taxonomy view modes.
 */
function _wishlist_template_term_view_mode_values() {
  // Grab the View Mode service.
  $entity_display_repository = \Drupal::service('entity_display.repository');

  // The entity type for which we are looking.
  $entity_type_id = "taxonomy_term";

  // Use the service to get an array of available modes.
  $view_modes = $entity_display_repository->getViewModes($entity_type_id);

  // Create a simple "allowed_values" array
  $allowed_values = array();
  foreach ($view_modes as $id => $view_mode) {
    $allowed_values[$id] = $view_mode['label'] . ' (' . $id . ')';
  }

  return $allowed_values;
}
