commerce_wishlist.commerce_wishlist_type.*:
  type: config_entity
  label: 'Wishlist type'
  mapping:
    label:
      type: label
      label: 'Label'
    id:
      type: string
      label: 'Machine-readable name'
    allowAnonymous:
      type: boolean
      label: 'Allow anonymous wishlists'
    allowMultiple:
      type: boolean
      label: 'Allow multiple wishlists'
    allowPublic:
      type: boolean
      label: 'Allow public wishlists'
    wishlistFormView:
      type: string
      label: 'Wishlist form view'

commerce_wishlist.commerce_wishlist_item_type.*:
  type: config_entity
  label: 'Wishlist item type'
  mapping:
    label:
      type: label
      label: 'Label'
    id:
      type: string
      label: 'Machine-readable name'
    purchasableEntityType:
      type: string
      label: 'Purchasable entity type'
    wishlistType:
      type: string
      label: 'Wishlist type'

block.settings.commerce_wishlist:
  type: block_settings
  label: 'Wishlist block'
  mapping:
    dropdown:
      type: boolean
      label: 'Display wishlist contents in dropdown'

commerce_product.commerce_product_type.*.third_party.commerce_wishlist:
  type: mapping
  label: 'Wishlist settings'
  mapping:
    show_wishlist:
      type: boolean
      label: 'Show wishlist button'
    weight_wishlist:
      type: integer
      label: 'Modify wishlist button sort order'
    label_wishlist:
      type: text
      label: 'Override the button label'

commerce_product.commerce_product_variation_type.*.third_party.commerce_wishlist:
  type: mapping
  label: 'Wishlist settings'
  mapping:
    wishlist_item_type:
      type: string
      label: 'Wishlist item type'
