wishlist_template.wishlist_template_type.*:
  type: config_entity
  label: 'Wishlist template type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
